server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379

  rabbitmq:
    port: 5672
    username: root
    password: 123123
    virtual-host: center

  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/dao/*.xml
  type-aliases-package: top.mnsx.sks_part.entity